jsf-etude-web/src/main/java/org/amicofragile/jsfetude/web/ContextBean.java
package org.amicofragile.jsfetude.web;

import java.io.Serializable;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

public class ContextBean implements Serializable {
	private static Map<String, Object> countries;

	static {
		countries = new LinkedHashMap<String, Object>();
		countries.put("English", Locale.ENGLISH);
		countries.put("Italiano", Locale.ITALY);
		countries.put("Deutsch", Locale.GERMAN);
		countries.put("Francais", Locale.FRENCH);
	}

	private String localeCode;

	public String getLocaleCode() {
		return localeCode;
	}

	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}

	public Date getCurrentTime() {
		return new Date();
	}

	public Map<String, Object> getCountriesInMap() {
		return countries;
	}

	public void countryLocaleCodeChanged(ValueChangeEvent e) {
		String newLocaleValue = e.getNewValue().toString();
		for (Map.Entry<String, Object> entry : countries.entrySet()) {
			if (entry.getValue().toString().equals(newLocaleValue)) {
				System.out.println("Selected locale " + newLocaleValue);
				FacesContext.getCurrentInstance().getViewRoot().setLocale((Locale) entry.getValue());
				break;
			}
		}
	}
}

jsf-etude-web/src/main/java/org/amicofragile/jsfetude/web/conditional/TestBean.java
package org.amicofragile.jsfetude.web.conditional;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name = "test")
@RequestScoped
public class TestBean {
	private Integer value;
	
	public void setValue(Integer value) {
		this.value = value;
	}
	
	public Integer getValue() {
		return value;
	}
}

jsf-etude-web/src/main/java/org/amicofragile/jsfetude/web/hello/HelloBean.java
package org.amicofragile.jsfetude.web.hello;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;

@ManagedBean(name = "hello")
@SessionScoped
public class HelloBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private String name = "Name here!";

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSayWelcome() {
		if ("".equals(name) || name == null) {
			return "";
		} else {
			return "Ajax message : Welcome " + name;
		}
	}
	
	public String upperWelcome() {
		if(name != null) {
			name = name.toUpperCase();
		}
		return "upper";
	}
}

jsf-etude-web/src/main/webapp/hello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:head>
        <title><h:outputText value="#{msg['hello.title']}" /></title>
        <h:outputStylesheet name="simple.css" library="styles" />
    </h:head>
    <h:body>
    	<h3 class="title"><h:outputText value="#{msg['hello.title']}" /></h3>
    	<h:form>
    	   <h:inputText value="#{hello.name}"></h:inputText>
    	   <h:commandButton value="Welcome Me" action="welcome?faces-redirect=true"></h:commandButton>
    	   <h:commandButton value="WELCOME" action="#{hello.upperWelcome}"></h:commandButton>
    	</h:form>
    	<h:form>
    		Language : <h:selectOneMenu value="#{ctx.localeCode}" onchange="submit()" 
    			valueChangeListener="#{ctx.countryLocaleCodeChanged}">
	   				<f:selectItems value="#{ctx.countriesInMap}" /> 
	   			</h:selectOneMenu>
    	</h:form>
    	<h:graphicImage library="images" name="arrow_red.png" />
    </h:body>
</html>

jsf-etude-web/src/main/webapp/helloAjax.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html">
 	<h:head></h:head>
    <h:body>
    	<h3>JSF 2.0 + Ajax Hello World Example @ #{ctx.currentTime}</h3>
 
    	<h:form>
    	   <h:inputText id="name" value="#{hello.name}"></h:inputText>
    	   <h:commandButton value="Welcome Me">
    		 <f:ajax execute="name" render="output" />
    	   </h:commandButton>
 
    	   <h2><h:outputText id="output" value="#{hello.sayWelcome}" /></h2>	
    	</h:form>
 
    </h:body>
</html>

jsf-etude-web/src/main/webapp/high.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:body>
	    <h2>High value</h2>
		<p>
			Value is <strong>#{test.value}</strong>
		</p>
		<h:form>
			<h:commandButton action="start" value="Back" />
		</h:form>
	</h:body>
</html>

jsf-etude-web/src/main/webapp/low.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:body>
    	<h2>Low value</h2>
		<p>
			Value is <em>#{test.value}</em>...
		</p>
		<h:form>
			<h:commandButton action="start" value="Back" />
		</h:form>
	</h:body>
</html>

jsf-etude-web/src/main/webapp/start.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:body>
	<h:form>
		<h:inputText value="#{test.value}"></h:inputText>
    	<h:commandButton action="choose" value="Choose" />
	</h:form>
    </h:body>
</html>

jsf-etude-web/src/main/webapp/welcome.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"    
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:head>
    	<title>JSF 2.0 Hello World</title>
    </h:head>
    <h:body bgcolor="white">
    	<h3>JSF 2.0 Hello World Example - welcome.xhtml</h3>
    	<h4>Welcome '<em>#{hello.name}</em>'</h4>
    	<a href="hello.xhtml">Back</a>
    </h:body>
</html>